### PR TITLE
Space freed

### PR DESCRIPTION
**Pull request by keshav1245**
Deleted org_struct.png that is The flowchart image in png format
org_struct.svg already present in its place so by deleting it 706 KB Space is freed

### CODE REVIEW

**Review by theNaut1lus — APPROVED** [review]

**Comment by theNaut1lus** [comment]
Will resolve this conflict tomorrow, just left it at review.

**Comment by keshav1245** [comment]
In the latest commit i have correct the title for about.html and activity.html page 
Before it was Punjab printing press but now they have been changed to corressponding pages i.e About us and Our activities respectively

**Comment by theNaut1lus** [comment]
Add the deleted file, as it is causing unnecessary conflicts 
Make an issue to remove unnecessary files and i will directly commit the removal

**Comment by keshav1245** [comment]
Deleted file added againa successfully 
Also with second commit it fixes #32

**Pull request merged**
